# Generated by Django 4.2.24 on 2025-09-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='logo_base64',
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da empresa (JPEG/PNG)', null=True, upload_to='logos/'),
        ),
    ]
